use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use clap::{CommandFactory, Parser};
use clap_markdown_generator::{
    MarkdownOptions,
    ParameterHeadingStyle,
};
use xelis_daemon::cli_config::CliConfig as DaemonConfig;
use xelis_wallet::config::Config as WalletConfig;
use xelis_miner::Config as MinerConfig;

#[derive(Parser)]
#[command(about = "Generate XELIS CLI configuration documentation.")]
struct Cli {
    /// Directory where the generated MDX files will be written.
    #[arg(long, default_value = "definitions/configuration")]
    output_dir: PathBuf,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let repo_root = repo_root()?;
    let output_dir = repo_root.join(cli.output_dir);

    fs::create_dir_all(&output_dir)
        .with_context(|| format!("creating output directory {}", output_dir.display()))?;

    write_config_docs::<DaemonConfig>(&output_dir, "xelis_daemon", "xelis_daemon.generated.mdx")?;
    write_config_docs::<WalletConfig>(&output_dir, "xelis_wallet", "xelis_wallet.generated.mdx")?;
    write_config_docs::<MinerConfig>(&output_dir, "xelis_miner", "xelis_miner.generated.mdx")
}

fn repo_root() -> Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .context("resolving repository root")
}

fn write_config_docs<T>(output_dir: &Path, command_name: &str, file_name: &str) -> Result<()>
where
    T: CommandFactory,
{
    let mut options = MarkdownOptions::default();
    options.include_toc = false;
    options.summary.enabled = false;
    options.include_html_anchors = false;
    options.parameter_heading = ParameterHeadingStyle::Name;

    let markdown =
        clap_markdown_generator::generate_markdown_for_command_with_options(T::command(), options);
    let markdown = as_embedded_reference(markdown, command_name);
    let content =
        format!("{{/* This file is @generated by crates/xelis-config-docs. */}}\n\n{markdown}");
    let path = output_dir.join(file_name);

    fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("generated {}", path.display());

    Ok(())
}

fn as_embedded_reference(markdown: String, command_name: &str) -> String {
    markdown
        .replace(&format!("# `{command_name}`"), "## Configuration")
        .replace("## Parameters", "### Parameters")
        .replace("\n### `", "\n#### `")
}
