use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use clap::{CommandFactory, Parser};
use xelis_daemon::cli_config::CliConfig as DaemonConfig;
use xelis_wallet::config::Config as WalletConfig;

#[derive(Parser)]
#[command(about = "Generate XELIS CLI configuration documentation.")]
struct Cli {
    /// Directory where the generated MDX files will be written.
    #[arg(long, default_value = "definitions/configuration")]
    output_dir: PathBuf,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let repo_root = repo_root()?;
    let output_dir = repo_root.join(cli.output_dir);

    fs::create_dir_all(&output_dir)
        .with_context(|| format!("creating output directory {}", output_dir.display()))?;

    write_config_docs(
        &output_dir,
        "xelis_daemon",
        "xelis_daemon.generated.mdx",
        DaemonConfig::command(),
    )?;
    write_config_docs(
        &output_dir,
        "xelis_wallet",
        "xelis_wallet.generated.mdx",
        WalletConfig::command(),
    )
}

fn repo_root() -> Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .context("resolving repository root")
}

fn write_config_docs(
    output_dir: &Path,
    command_name: &str,
    file_name: &str,
    command: clap::Command,
) -> Result<()> {
    let markdown = clap_markdown::generate_markdown_for_command(command);
    let markdown = as_embedded_reference(markdown, command_name);
    let content =
        format!("{{/* This file is @generated by crates/xelis-config-docs. */}}\n\n{markdown}");
    let path = output_dir.join(file_name);

    fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("generated {}", path.display());

    Ok(())
}

fn as_embedded_reference(markdown: String, command_name: &str) -> String {
    markdown
        .replace(&format!("# `{command_name}`"), "## Configuration Reference")
        .replace("## Parameters", "### Parameters")
        .replace("\n### `", "\n#### `")
}
